name: Deploy bot to EC2

on:
  push:
    branches: [ "main-1" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: SSH to EC2 and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.AWS_KEY }}
        port: 22
        script: |
          cd ~/sample-bot
          git pull origin main-1
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pkill -f trading_bot.py || true
          nohup python3 trading_bot.py > trading_bot.log 2>&1 &
